
# Code Highlight theme
# Available value:
#    normal | night | night yilia | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
# night yilia - https://github.com/litten/hexo-theme-yilia
highlight_theme: normal

color:
  header: indigo
  footer: indigo
  page_nav: indigo
  side_nav: indigo darken-1
  tag: pink lighten-1
  article_title_link: indigo
  link: pink
  pagination: pink
  tab: pink
  archive_item: grey
  fab: pink
  fab_2: green
  fab_3: yellow darken-1
  new: pink
  about_header: indigo
  about_title: indigo

archive_yearly: true
